const assert=require('node:assert/strict');
require('../ctv_web/js/event-playback.js');
const E=globalThis.CtvEventPlayback;
const segment=(id,start,type)=>({id,start_ts:start,end_ts:start+4,events:[{type,timestamp:start+1}]});
const original={cameras:[{camera_id:1,segments:[segment(1,0,'vehicle'),segment(2,4,'person'),segment(3,8,'vehicle')]},{camera_id:2,segments:[segment(4,0,'person'),segment(5,4,'animal'),segment(6,8,'vehicle')]}]};
const cars=E.filterTimeline(original,new Set(['vehicle']));
assert.deepEqual(cars.cameras.map(c=>c.segments.map(s=>s.id)),[[1,3],[6]]);
assert.equal(E.playableTime(cars,[1,2],4),8);
assert.equal(E.playableTime(cars,[2],0),8);
assert.equal(E.playableTime(cars,[1,2],12),null);
assert.equal(E.playableTime(cars,[1],2),2);
const either=E.filterTimeline(original,new Set(['vehicle','person']));
assert.deepEqual(either.cameras.map(c=>c.segments.map(s=>s.id)),[[1,2,3],[4,6]]);
assert.equal(E.filterTimeline(original,new Set()).cameras[0].segments.length,3);
assert.equal(original.cameras[0].segments.length,3);
const events=[{type:'person',timestamp:10,end_timestamp:20},{type:'vehicle',timestamp:12}];
assert.deepEqual(E.activeTypes(events,9),[]);
assert.deepEqual(E.activeTypes(events,12),['person','vehicle']);
assert.deepEqual(E.activeTypes(events,15),['person']);
assert.deepEqual(E.activeTypes(events,20),[]);
assert.equal(E.eventEnd({timestamp:10,end_timestamp:9}),13);
console.log('Event filters, playback gaps, durations and fallback tests passed');
